### ISSUE TITLE
LHCb example isn't working?

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#482]
Hi all,

I assume this isn't just me?

If I go to: 
https://hepsoftwarefoundation.org/phoenix/#/lhcb

it fails with:
```
Failed to load resource: the server responded with a status of 404 ()
url-options-manager.ts:114 Could not find the file specified in URL. SyntaxError: Unexpected token < in JSON at position 0
(anonymous) @ url-options-manager.ts:114
/phoenix/assets/geometry/LHCb/LHCb.gltf:1          Failed to load resource: the server responded with a status of 404 ()
core.mjs:6494 ERROR Error: Uncaught (in promise): Error: fetch for "https://hepsoftwarefoundation.org/phoenix/assets/geometry/LHCb/LHCb.gltf" responded with 404: 
Error: fetch for "https://hepsoftwarefoundation.org/phoenix/assets/geometry/LHCb/LHCb.gltf" responded with 404: 
    at three.module.js:39338:12
    at v.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:25608:33)
    at v.invoke (zone.js:371:52)
    at M.run (zone.js:134:43)
    at zone.js:1275:36
    at v.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25595:33)
    at v.invokeTask (zone.js:405:60)
    at M.runTask (zone.js:178:47)
    at z (zone.js:1211:31)
    at zone.js:1118:17
    at l (cjs.js:74:89)
    at v.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:25608:33)
    at v.invoke (zone.js:371:52)
    at M.run (zone.js:134:43)
    at zone.js:1275:36
    at v.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25595:33)
```

**Comment by sponce** [comment]
I must say I had not tried that for long. I'm only using http://phoenix-dev.surge.sh/#/lhcb.
So what's used there ? Latest release ?

**Comment by sponce** [comment]
I do not really understand the problem. The gltf file is there in the v2.9.0 tag and seems to have proper content. @9inpachi could it be that the deployment has troubles, rather than the code ?

**Comment by 9inpachi** [comment]
LHCb is up again with the new release (v2.10.0): https://hepsoftwarefoundation.org/phoenix/#/lhcb
