### ISSUE TITLE
Problem with io-options-dialog.component.test.ts

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#606]
Runing tests locally, I get a failure in `io-options-dialog.component.test.ts`
```bash
 /home/emoyse/phoenix/packages/phoenix-event-display/dist/loaders/jivexml-loader.js:35
                   eventNumber: firstEvent.getAttribute('eventNumber'),
                                           ^
       
       TypeError: Cannot read properties of undefined (reading 'getAttribute')
           at JiveXMLLoader.getEventData (/home/emoyse/phoenix/packages/phoenix-event-display/src/loaders/jivexml-loader.ts:43:24)
           at /home/emoyse/phoenix/packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts:2857:44
           at Array.forEach (<anonymous>)
           at IOOptionsDialogComponent.handleZipEventDataInput (/home/emoyse/phoenix/packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.ts:2850:8)
           at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Looking at the code, I'm wondering about this:
https://github.com/HSF/phoenix/blob/847372e0d73c45a4ef5639773e564a99afcaf260/packages/phoenix-ng/projects/phoenix-ui-components/lib/components/ui-menu/io-options/io-options-dialog/io-options-dialog.component.test.ts#L90

Edit: I was being stupid. So I'm not sure what the issue is (I checked that the URL is correct). But I'll have a look again next week.

**Comment by EdwardMoyse** [comment]
@9inpachi would you be able to look at this? I've spent hours on it now and I'm completely baffled. 

I tried changing this:
        'https://github.com/HSF/phoenix/blob/master/packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML/JiveXML_336567_2327102923.xml',
to `https://raw.githubusercontent.com/HSF/phoenix/main/packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML/JiveXML_336567_2327102923.xml`  but it didn't help. 

I'm pretty sure, from debugging, that the file is retrieved correctly. At least, `res` seems to be the raw XML file, when I make the above change. But then something goes wrong afterwards and eventually in  `getEventData` in `JiveXMLLoader` `this.data` is:
```
"{\"payload\":{\"allShortcutsEnabled\":false,\"fileTree\":{\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML\":{\"items\":[{\"name\":\"JiveXML_336567_2327102923.xml\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML/JiveXML_336567_2327102923.xml\",\"contentType\":\"file\"},{\"name\":\"JiveXML_359310_3066561649.xml\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML/JiveXML_359310_3066561649.xml\",\"contentType\":\"file\"}],\"totalCount\":2},\"packages/phoenix-ng/projects/phoenix-app/src/assets/files\":{\"items\":[{\"name\":\"JiveXML\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML\",\"contentType\":\"directory\"},{\"name\":\"TrackML\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/TrackML\",\"contentType\":\"directory\"},{\"name\":\"cms\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/cms\",\"contentType\":\"directory\"},{\"name\":\"config\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/config\",\"contentType\":\"directory\"},{\"name\":\"event_data\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/event_data\",\"contentType\":\"directory\"},{\"name\":\"lhcb\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/lhcb\",\"contentType\":\"directory\"},{\"name\":\"phnx\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/phnx\",\"contentType\":\"directory\"},{\"name\":\"root\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/root\",\"contentType\":\"directory\"}],\"totalCount\":8},\"packages/phoenix-ng/projects/phoenix-app/src/assets\":{\"items\":[{\"name\":\"favicon\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/favicon\",\"contentType\":\"directory\"},{\"name\":\"files\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files\",\"contentType\":\"directory\"},{\"name\":\"fonts\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/fonts\",\"contentType\":\"directory\"},{\"name\":\"geometry\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/geometry\",\"contentType\":\"directory\"},{\"name\":\"icons\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/icons\",\"contentType\":\"directory\"},{\"name\":\"images\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/images\",\"contentType\":\"directory\"},{\"name\":\"preset-views\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/preset-views\",\"contentType\":\"directory\"},{\"name\":\".gitkeep\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/.gitkeep\",\"contentType\":\"file\"}],\"totalCount\":8},\"packages/phoenix-ng/projects/phoenix-app/src\":{\"items\":[{\"name\":\"app\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/app\",\"contentType\":\"directory\"},{\"name\":\"assets\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets\",\"contentType\":\"directory\"},{\"name\":\"environments\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/environments\",\"contentType\":\"directory\"},{\"name\":\"favicon.ico\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/favicon.ico\",\"contentType\":\"file\"},{\"name\":\"index.html\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/index.html\",\"contentType\":\"file\"},{\"name\":\"main.ts\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/main.ts\",\"contentType\":\"file\"},{\"name\":\"polyfills.ts\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/polyfills.ts\",\"contentType\":\"file\"},{\"name\":\"styles.scss\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/styles.scss\",\"contentType\":\"file\"},{\"name\":\"test.ts\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/test.ts\",\"contentType\":\"file\"},{\"name\":\"zone-flags.ts\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/zone-flags.ts\",\"contentType\":\"file\"}],\"totalCount\":10},\"packages/phoenix-ng/projects/phoenix-app\":{\"items\":[{\"name\":\"cypress\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/cypress\",\"contentType\":\"directory\"},{\"name\":\"src\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/src\",\"contentType\":\"directory\"},{\"name\":\"browserslist\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/browserslist\",\"contentType\":\"file\"},{\"name\":\"event-config.json\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/event-config.json\",\"contentType\":\"file\"},{\"name\":\"tsconfig.app.json\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/tsconfig.app.json\",\"contentType\":\"file\"},{\"name\":\"tsconfig.spec.json\",\"path\":\"packages/phoenix-ng/projects/phoenix-app/tsconfig.spec.json\",\"contentType\":\"file\"}],\"totalCount\":6},\"packages/phoenix-ng/projects\":{\"items\":[{\"name\":\"phoenix-app\",\"path\":\"packages/phoenix-ng/projects/phoenix-app\",\"contentType\":\"directory\"},{\"name\":\"phoenix-ui-components\",\"path\":\"packages/phoenix-ng/projects/phoenix-ui-components\",\"contentType\":\"directory\"}],\"totalCount\":2},\"packages/phoenix-ng\":{\"items\":[{\"name\":\"projects\",\"path\":\"packages/phoenix-ng/projects\",\"contentType\":\"directory\"},{\"name\":\".editorconfig\",\"path\":\"packages/phoenix-ng/.editorconfig\",\"contentType\":\"file\"},{\"name\":\"CHANGELOG.md\",\"path\":\"packages/phoenix-ng/CHANGELOG.md\",\"contentType\":\"file\"},{\"name\":\"README.md\",\"path\":\"packages/phoenix-ng/README.md\",\"contentType\":\"file\"},{\"name\":\"angular.json\",\"path\":\"packages/phoenix-ng/angular.json\",\"contentType\":\"file\"},{\"name\":\"cypress.config.ts\",\"path\":\"packages/phoenix-ng/cypress.config.ts\",\"contentType\":\"file\"},{\"name\":\"jest-global-mocks.ts\",\"path\":\"packages/phoenix-ng/jest-global-mocks.ts\",\"contentType\":\"file\"},{\"name\":\"jest.config.js\",\"path\":\"packages/phoenix-ng/jest.config.js\",\"contentType\":\"file\"},{\"name\":\"package.json\",\"path\":\"packages/phoenix-ng/package.json\",\"contentType\":\"file\"},{\"name\":\"setup-jest.ts\",\"path\":\"packages/phoenix-ng/setup-jest.ts\",\"contentType\":\"file\"},{\"name\":\"tsconfig.json\",\"path\":\"packages/phoenix-ng/tsconfig.json\",\"contentType\":\"file\"},{\"name\":\"tsconfig.spec.json\",\"path\":\"packages/phoenix-ng/tsconfig.spec.json\",\"contentType\":\"file\"}],\"totalCount\":12},\"packages\":{\"items\":[{\"name\":\"phoenix-event-display\",\"path\":\"packages/phoenix-event-display\",\"contentType\":\"directory\"},{\"name\":\"phoenix-ng\",\"path\":\"packages/phoenix-ng\",\"contentType\":\"directory\"}],\"totalCount\":2},\"\":{\"items\":[{\"name\":\".github\",\"path\":\".github\",\"contentType\":\"directory\"},{\"name\":\".husky\",\"path\":\".husky\",\"contentType\":\"directory\"},{\"name\":\".vscode\",\"path\":\".vscode\",\"contentType\":\"directory\"},{\"name\":\".yarn\",\"path\":\".yarn\",\"contentType\":\"directory\"},{\"name\":\"docs\",\"path\":\"docs\",\"contentType\":\"directory\"},{\"name\":\"guides\",\"path\":\"guides\",\"contentType\":\"directory\"},{\"name\":\"packages\",\"path\":\"packages\",\"contentType\":\"directory\"},{\"name\":\".dockerignore\",\"path\":\".dockerignore\",\"contentType\":\"file\"},{\"name\":\".eslintrc.json\",\"path\":\".eslintrc.json\",\"contentType\":\"file\"},{\"name\":\".gitignore\",\"path\":\".gitignore\",\"contentType\":\"file\"},{\"name\":\".lintstagedrc.json\",\"path\":\".lintstagedrc.json\",\"contentType\":\"file\"},{\"name\":\".prettierignore\",\"path\":\".prettierignore\",\"contentType\":\"file\"},{\"name\":\".prettierrc\",\"path\":\".prettierrc\",\"contentType\":\"file\"},{\"name\":\".yarnrc.yml\",\"path\":\".yarnrc.yml\",\"contentType\":\"file\"},{\"name\":\"CHANGELOG.md\",\"path\":\"CHANGELOG.md\",\"contentType\":\"file\"},{\"name\":\"CONTRIBUTING.md\",\"path\":\"CONTRIBUTING.md\",\"contentType\":\"file\"},{\"name\":\"Dockerfile\",\"path\":\"Dockerfile\",\"contentType\":\"file\"},{\"name\":\"Dockerfile.gl\",\"path\":\"Dockerfile.gl\",\"contentType\":\"file\"},{\"name\":\"LICENSE\",\"path\":\"LICENSE\",\"contentType\":\"file\"},{\"name\":\"README.md\",\"path\":\"README.md\",\"contentType\":\"file\"},{\"name\":\"lerna.json\",\"path\":\"lerna.json\",\"contentType\":\"file\"},{\"name\":\"package.json\",\"path\":\"package.json\",\"contentType\":\"file\"},{\"name\":\"yarn.lock\",\"path\":\"yarn.lock\",\"contentType\":\"file\"}],\"totalCount\":23}},\"fileTreeProcessingTime\":11.209537000000001,\"foldersToFetch\":[],\"reducedMotionEnabled\":null,\"repo\":{\"id\":135442382,\"defaultBranch\":\"main\",\"name\":\"phoenix\",\"ownerLogin\":\"HSF\",\"currentUserCanPush\":false,\"isFork\":false,\"isEmpty\":false,\"createdAt\":\"2018-05-30T12:53:07.000Z\",\"ownerAvatar\":\"https://avatars.githubusercontent.com/u/11518194?v=4\",\"public\":true,\"private\":false,\"isOrgOwned\":true},\"symbolsExpanded\":false,\"treeExpanded\":true,\"refInfo\":{\"name\":\"main\",\"listCacheKey\":\"v0:1692361424.0\",\"canEdit\":false,\"refType\":\"branch\",\"currentOid\":\"847372e0d73c45a4ef5639773e564a99afcaf260\"},\"path\":\"packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML/JiveXML_336567_2327102923.xml\",\"currentUser\":null,\"blob\":{\"rawLines\":[],\"stylingDirectives\":[],\"csv\":null,\"csvError\":null,\"dependabotInfo\":{\"showConfigurationBanner\":false,\"configFilePath\":null,\"networkDependabotPath\":\"/HSF/phoenix/network/updates\",\"dismissConfigurationNoticePath\":\"/settings/dismiss-notice/dependabot_configuration_notice\",\"configurationNoticeDismissed\":null,\"repoAlertsPath\":\"/HSF/phoenix/security/dependabot\",\"repoSecurityAndAnalysisPath\":\"/HSF/phoenix/settings/security_analysis\",\"repoOwnerIsOrg\":true,\"currentUserCanAdminRepo\":false},\"displayName\":\"JiveXML_336567_2327102923.xml\",\"displayUrl\":\"https://github.com/HSF/phoenix/blob/main/packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML/JiveXML_336567_2327102923.xml?raw=true\",\"headerInfo\":{\"blobSize\":\"12.4 MB\",\"deleteInfo\":{\"deleteTooltip\":\"You must be signed in to make or propose changes\"},\"editInfo\":{\"editTooltip\":\"You must be signed in to make or propose changes\"},\"ghDesktopPath\":\"https://desktop.github.com\",\"gitLfsPath\":null,\"onBranch\":true,\"shortPath\":\"1313ad4\",\"siteNavLoginPath\":\"/login?return_to=https%3A%2F%2Fgithub.com%2FHSF%2Fphoenix%2Fblob%2Fmain%2Fpackages%2Fphoenix-ng%2Fprojects%2Fphoenix-app%2Fsrc%2Fassets%2Ffiles%2FJiveXML%2FJiveXML_336567_2327102923.xml\",\"isCSV\":false,\"isRichtext\":false,\"toc\":null,\"lineInfo\":{\"truncatedLoc\":null,\"truncatedSloc\":null},\"mode\":\"file\"},\"image\":false,\"isCodeownersFile\":null,\"isPlain\":false,\"isValidLegacyIssueTemplate\":false,\"issueTemplateHelpUrl\":\"https://docs.github.com/articles/about-issue-and-pull-request-templates\",\"issueTemplate\":null,\"discussionTemplate\":null,\"language\":null,\"languageID\":null,\"large\":true,\"loggedIn\":false,\"newDiscussionPath\":\"/HSF/phoenix/discussions/new\",\"newIssuePath\":\"/HSF/phoenix/issues/new\",\"planSupportInfo\":{\"repoIsFork\":null,\"repoOwnedByCurrentUser\":null,\"requestFullPath\":\"/HSF/phoenix/blob/main/packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML/JiveXML_336567_2327102923.xml\",\"showFreeOrgGatedFeatureMessage\":null,\"showPlanSupportBanner\":null,\"upgradeDataAttributes\":null,\"upgradePath\":null},\"publishBannersInfo\":{\"dismissActionNoticePath\":\"/settings/dismiss-notice/publish_action_from_dockerfile\",\"dismissStackNoticePath\":\"/settings/dismiss-notice/publish_stack_from_file\",\"releasePath\":\"/HSF/phoenix/releases/new?marketplace=true\",\"showPublishActionBanner\":false,\"showPublishStackBanner\":false},\"renderImageOrRaw\":true,\"richText\":null,\"renderedFileInfo\":null,\"shortPath\":null,\"tabSize\":2,\"topBannersInfo\":{\"overridingGlobalFundingFile\":false,\"globalPreferredFundingPath\":null,\"repoOwner\":\"HSF\",\"repoName\":\"phoenix\",\"showInvalidCitationWarning\":false,\"citationHelpUrl\":\"https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files\",\"showDependabotConfigurationBanner\":false,\"actionsOnboardingTip\":null},\"truncated\":true,\"viewable\":false,\"workflowRedirectUrl\":null,\"symbols\":{\"timedOut\":true,\"notAnalyzed\":true,\"symbols\":[],\"error\":{\"code\":\"invalid_argument\",\"msg\":\"content required\",\"meta\":{}}}},\"copilotInfo\":null,\"csrf_tokens\":{\"/HSF/phoenix/branches\":{\"post\":\"U7K5NFDqhPrOONpELJzPP8i678M_MI-EoZCh9Wg2yLIGvanug0Q7PaIsvcVCQ1P9AFX-2Nznm_Uijild3QtzeA\"},\"/repos/preferences\":{\"post\":\"G8ngFrI6ksIvoguTFiWfKE0uHmBm1TW5_TJLtc52dR3zIiuNUPYN_J6G8zcuvAaJfaPw270HSPczFvF2QAwzjA\"}}},\"title\":\"phoenix/packages/phoenix-ng/projects/phoenix-app/src/assets/files/JiveXML/JiveXML_336567_2327102923.xml at main � HSF/phoenix\"}"\
```

which does NOT seem correct - aside from the fact it doesn't seem to contain the XML data, the event mentioned here here is local, and has the wrong name (it should be `JiveXML_336567_2327102923.xml`).

Looking a bit earlier, in `handleJiveXMLDataInput` 
```typescript
  handleJiveXMLDataInput(files: FileList) {
    const callback = (content: any) => {
      const jiveloader = new JiveXMLLoader();
      jiveloader.process(content);
      const eventData = jiveloader.getEventData();
      this.eventDisplay.buildEventDataFromJSON(eventData);
    };
    const file = files[0];
    this.handleFileInput(files[0], 'xml', callback);
  }
```

`files` seems to be empty? Or  rather, to contain an empty File object.
```
{
  "0": {
  },
  length: 1,
  item: (index) => files[index],
}
```

**Comment by 9inpachi** [comment]
Hey Ed,

I checked this out last night and it seemed to have been a problem with the files URL. Since we updated the branch from `master` to `main` it was trying to read from the `master` branch. And also the file URL was not raw so not sure if it worked before either. 

Not sure how you were able to see that the data is there. It may be that you updated one instance of the GitHub URL occurrence and that fixed the first issue but since there are two you will end up seeing the error for the second one in the test run.

I have created a PR for the fix which you can check.

**Comment by EdwardMoyse** [comment]
Hi @9inpachi - thank you so much for this! 

I guess I accidentally fixed the master/main issue when fixing the URL to be raw, but just didn't realise it was in two places. It's good you spotted this though - we had a few more links to master in the codebase (see #615)
