### ISSUE TITLE
Build release action no longer working

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#645]
```
Successfully replaced in file /home/runner/work/phoenix/phoenix/docs/api-docs/index.html
file:///home/runner/work/phoenix/phoenix/node_modules/prettier/index.mjs:22061
        throw new UndefinedParserError(
              ^

UndefinedParserError: No parser could be inferred for file "/home/runner/work/phoenix/phoenix/yarn.lock".
    at normalizeFormatOptions (file:///home/runner/work/phoenix/phoenix/node_modules/prettier/index.mjs:22061:15)
    at formatWithCursor (file:///home/runner/work/phoenix/phoenix/node_modules/prettier/index.mjs:22794:52)
    at file:///home/runner/work/phoenix/phoenix/node_modules/prettier/index.mjs:24189:12
    at async Module.format2 (file:///home/runner/work/phoenix/phoenix/node_modules/prettier/index.mjs:24194:25)

Node.js v18.19.1
```

I have not yet been able to reproduce this locally.

https://github.com/HSF/phoenix/actions/runs/8338646866

**Comment by EdwardMoyse** [comment]
Fixed.

**Comment by EdwardMoyse** [comment]
Argh. Except that it seems like it hasn't pushed to npm:
https://www.npmjs.com/package/phoenix-event-display

But this might be because of my previous efforts locally (see #649 ):

From the [log](https://github.com/HSF/phoenix/actions/runs/8378588447/job/22943489893)
```
lerna info current version 2.15.0
lerna notice Current HEAD is already released, skipping change detection.
lerna success No changed packages to publish
```

**Comment by EdwardMoyse** [comment]
Still not working. See this in the log:
```
Error: Could not find the '@angular-devkit/ng-packagr:build' builder's node package.
lerna ERR! lifecycle "prepublishOnly" errored in "phoenix-ui-components", exiting 1
```

Presumably related to: #644

**Comment by EdwardMoyse** [comment]
I do not see this error locally - but locally it seems to stop just before this i.e. with 
```
Successfully replaced in file /Users/emoyse/LocalDocuments/phoenix/docs/api-docs/index.html
lerna info git Pushing tags...
lerna info publish Publishing packages to npm...
lerna success All packages have already been published.
```

What I do not understand is why the git action is doing more than this?

https://github.com/HSF/phoenix/blob/3154d140e13c1eba609226e5fcf327b3db5f4f11/.github/workflows/release.yml#L40-L44

This seems to be exactly what is done locally. 

Also, why does npm publish not work here, despite lerna saying it has?
```
lerna info publish Publishing packages to npm...
```

@9inpachi If you have any time to look at this, I would be very grateful. I urgently need to publish a new version of PhoenixATLAS and I'm running out of ideas here.

**Comment by EdwardMoyse** [comment]
Ah. I suspect part of the issue might be related to moving to angular 17... I think `angular.json` might need updating.

**Comment by EdwardMoyse** [comment]
Possibly fixed!
